// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TechCatRegistry.Data;

#nullable disable

namespace TechCatRegistry.Data.Migrations
{
    [DbContext(typeof(TechCatDbContext))]
    [Migration("20260909153932_InitialSchema")]
    partial class InitialSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TechCatRegistry.Core.Catalog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("PublishedOn")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.ToTable("Catalog");
                });

            modelBuilder.Entity("TechCatRegistry.Core.Component", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CatalogId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("SheetCode")
                        .IsRequired()
                        .HasMaxLength(31)
                        .HasColumnType("nvarchar(31)");

                    b.HasKey("Id");

                    b.HasIndex("CatalogId", "SheetCode")
                        .IsUnique();

                    b.ToTable("Component");
                });

            modelBuilder.Entity("TechCatRegistry.Core.DataPoint", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ComponentId")
                        .HasColumnType("int");

                    b.Property<string>("Estimate")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<decimal?>("NumericValue")
                        .HasPrecision(18, 6)
                        .HasColumnType("decimal(18,6)");

                    b.Property<int>("ParameterId")
                        .HasColumnType("int");

                    b.Property<int?>("PriceYear")
                        .HasColumnType("int");

                    b.Property<string>("TxtValue")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ParameterId");

                    b.HasIndex("ComponentId", "ParameterId", "Year", "Estimate")
                        .IsUnique();

                    b.ToTable("DataPoint", t =>
                        {
                            t.HasCheckConstraint("CK_DataPoint_Estimate", "[Estimate] IN ('ctrl', 'lower', 'upper')");

                            t.HasCheckConstraint("CK_DataPoint_ExactlyOneValue", "([NumericValue] IS NULL) <> ([TxtValue] IS NULL)");
                        });
                });

            modelBuilder.Entity("TechCatRegistry.Core.ParamGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("ParameterGroup");
                });

            modelBuilder.Entity("TechCatRegistry.Core.Parameter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("GroupId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<string>("Unit")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("GroupId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Parameter");
                });

            modelBuilder.Entity("TechCatRegistry.Core.Component", b =>
                {
                    b.HasOne("TechCatRegistry.Core.Catalog", "Catalog")
                        .WithMany("Components")
                        .HasForeignKey("CatalogId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Catalog");
                });

            modelBuilder.Entity("TechCatRegistry.Core.DataPoint", b =>
                {
                    b.HasOne("TechCatRegistry.Core.Component", "Component")
                        .WithMany("DataPoints")
                        .HasForeignKey("ComponentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TechCatRegistry.Core.Parameter", "Parameter")
                        .WithMany("Points")
                        .HasForeignKey("ParameterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Component");

                    b.Navigation("Parameter");
                });

            modelBuilder.Entity("TechCatRegistry.Core.Parameter", b =>
                {
                    b.HasOne("TechCatRegistry.Core.ParamGroup", "Group")
                        .WithMany("Parameters")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Group");
                });

            modelBuilder.Entity("TechCatRegistry.Core.Catalog", b =>
                {
                    b.Navigation("Components");
                });

            modelBuilder.Entity("TechCatRegistry.Core.Component", b =>
                {
                    b.Navigation("DataPoints");
                });

            modelBuilder.Entity("TechCatRegistry.Core.ParamGroup", b =>
                {
                    b.Navigation("Parameters");
                });

            modelBuilder.Entity("TechCatRegistry.Core.Parameter", b =>
                {
                    b.Navigation("Points");
                });
#pragma warning restore 612, 618
        }
    }
}
